'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import toast from 'react-hot-toast';
import { motion } from 'framer-motion';
import { ExperienceLevel } from '@intervu/shared';
import { interviewAPI } from '@/utils/api';
import AnimatedRoleSelector from '@/components/AnimatedRoleSelector';
import AnimatedLevelSelector from '@/components/AnimatedLevelSelector';
import { Loader2, Play, Target, Clock, Brain, Zap, Users, Award } from 'lucide-react';

export default function Home() {
  const router = useRouter();
  const [selectedRole, setSelectedRole] = useState<string>('');
  const [selectedLevel, setSelectedLevel] = useState<ExperienceLevel | ''>('');
  const [questionCount, setQuestionCount] = useState<number>(10);
  const [isLoading, setIsLoading] = useState(false);

  const handleGenerateInterview = async () => {
    if (!selectedRole || !selectedLevel) {
      toast.error('Please select both role and experience level');
      return;
    }
    setIsLoading(true);
    try {
      const response = await interviewAPI.generateInterview({
        role: selectedRole,
        experienceLevel: selectedLevel as ExperienceLevel,
        questionCount
      });
      if (response.success && response.interview) {
        toast.success('Interview generated successfully!');
        router.push(`/interview/${response.interview.id}`);
      } else {
        toast.error(response.error || 'Failed to generate interview');
      }
    } catch (error) {
      toast.error('Something went wrong. Please try again.');
      console.error('Error generating interview:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Questions',
      description: 'Dynamic questions generated by advanced AI models tailored to your role and experience level.'
    },
    {
      icon: Target,
      title: 'Role-Specific Content',
      description: 'Questions designed specifically for your target role and technology stack.'
    },
    {
      icon: Clock,
      title: 'Time Management',
      description: 'Practice with realistic time constraints to improve your interview performance.'
    },
    {
      icon: Users,
      title: 'Experience-Based',
      description: 'Adaptive difficulty based on your experience level from beginner to senior.'
    },
    {
      icon: Award,
      title: 'Performance Tracking',
      description: 'Track your progress and identify areas for improvement with detailed analytics.'
    },
    {
      icon: Zap,
      title: 'Instant Feedback',
      description: 'Get immediate feedback and explanations to accelerate your learning.'
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-blue-50 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900">
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-r from-blue-600/10 to-purple-600/10"></div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center"
          >
            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.2 }}
              className="text-5xl md:text-6xl font-bold text-gray-900 dark:text-white mb-6"
            >
              Master Your
              <span className="gradient-text"> Technical Interviews</span>
            </motion.h1>
            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.4 }}
              className="text-xl text-gray-600 dark:text-gray-300 mb-8 max-w-3xl mx-auto"
            >
              Prepare for technical interviews with AI-powered mock interviews tailored to your role, 
              experience level, and technology stack. Practice makes perfect!
            </motion.p>
          </motion.div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-16 bg-white dark:bg-gray-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.6 }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl font-bold text-gray-900 dark:text-white mb-4">
              Why Choose IntervU?
            </h2>
            <p className="text-lg text-gray-600 dark:text-gray-300">
              Advanced features designed to maximize your interview success
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.8, delay: 0.8 }}
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"
          >
            {features.map((feature, index) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.1 * index }}
                whileHover={{ y: -5 }}
                className="card p-6 text-center"
              >
                <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-purple-600 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <feature.icon className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">
                  {feature.title}
                </h3>
                <p className="text-gray-600 dark:text-gray-400">
                  {feature.description}
                </p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Interview Setup Section */}
      <section className="py-16 bg-gray-50 dark:bg-gray-900">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl font-bold text-gray-900 dark:text-white mb-4">
              Start Your Interview Preparation
            </h2>
            <p className="text-lg text-gray-600 dark:text-gray-300">
              Select your role and experience level to generate a personalized interview
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="space-y-8"
          >
            {/* Role Selection */}
            <AnimatedRoleSelector
              selectedRole={selectedRole}
              onRoleChange={setSelectedRole}
            />

            {/* Level Selection */}
            <AnimatedLevelSelector
              selectedLevel={selectedLevel}
              onLevelChange={setSelectedLevel}
            />

            {/* Question Count */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.4 }}
              className="space-y-4"
            >
              <div className="text-lg font-semibold text-gray-700 dark:text-gray-300">
                Number of Questions
              </div>
              <select
                value={questionCount}
                onChange={(e) => setQuestionCount(Number(e.target.value))}
                className="input-field"
              >
                <option value={5}>5 Questions (Quick Practice)</option>
                <option value={10}>10 Questions (Standard)</option>
                <option value={15}>15 Questions (Comprehensive)</option>
                <option value={20}>20 Questions (Deep Dive)</option>
              </select>
            </motion.div>

            {/* Generate Button */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.6 }}
            >
              <motion.button
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={handleGenerateInterview}
                disabled={isLoading || !selectedRole || !selectedLevel}
                className="w-full btn-primary py-4 text-lg flex items-center justify-center space-x-2 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isLoading ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    <span>Generating Interview...</span>
                  </>
                ) : (
                  <>
                    <Play className="w-5 h-5" />
                    <span>Generate Interview</span>
                  </>
                )}
              </motion.button>
            </motion.div>
          </motion.div>
        </div>
      </section>
    </div>
  );
} 